# Generated by Django 4.2.7 on 2023-11-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumPost', '0002_comment_creation_date_comment_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
