# Generated by Django 4.2.7 on 2023-11-16 23:32

import apps.forumPost.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumPost', '0003_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.forumPost.models.commentImageTo),
        ),
    ]
